<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9">
  <xsl:output method="html" encoding="UTF-8" indent="yes"/>

  <xsl:template match="/">
    <html lang="en">
      <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <meta name="robots" content="noindex"/>
        <title>9278.io — XML Sitemap</title>
        <style>
          :root { --blue:#2563eb; --ink:#0f172a; --muted:#64748b; --line:#e2e8f0; --bg:#f8fafc; }
          * { box-sizing:border-box; }
          body { margin:0; background:var(--bg); color:var(--ink);
            font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif; line-height:1.6; }
          .wrap { max-width:1000px; margin:0 auto; padding:40px 20px 64px; }
          header { margin-bottom:28px; }
          .brand { font-size:30px; font-weight:800; letter-spacing:-.02em; }
          .brand span { color:var(--blue); }
          h1 { font-size:24px; margin:14px 0 6px; letter-spacing:-.01em; }
          .sub { color:var(--muted); margin:0; font-size:15px; }
          .sub strong { color:var(--ink); }
          .card { margin-top:24px; background:#fff; border:1px solid var(--line);
            border-radius:16px; overflow:hidden; box-shadow:0 1px 3px rgba(15,23,42,.04); }
          table { width:100%; border-collapse:collapse; font-size:14px; }
          thead th { text-align:left; background:#f1f5f9; color:var(--muted); font-weight:600;
            text-transform:uppercase; letter-spacing:.05em; font-size:11px; padding:12px 16px; }
          tbody td { padding:12px 16px; border-top:1px solid var(--line); vertical-align:middle; }
          tbody tr:hover { background:#f8fafc; }
          td a { color:var(--blue); text-decoration:none; word-break:break-all; font-weight:500; }
          td a:hover { text-decoration:underline; }
          .num { color:var(--muted); width:46px; text-align:right; padding-right:8px; }
          .pill { display:inline-block; padding:2px 10px; border-radius:999px; font-size:12px;
            background:rgba(37,99,235,.08); color:var(--blue); border:1px solid rgba(37,99,235,.18); text-transform:capitalize; }
          .prio { font-variant-numeric:tabular-nums; color:var(--ink); font-weight:600; }
          .muted { color:var(--muted); }
          .foot { margin-top:20px; font-size:13px; color:var(--muted); }
          .foot a { color:var(--blue); text-decoration:none; }
          @media (max-width:640px){ .hide-sm{ display:none; } h1{font-size:20px;} .brand{font-size:24px;} }
        </style>
      </head>
      <body>
        <div class="wrap">
          <header>
            <div class="brand">9278<span>.io</span></div>
            <h1>XML Sitemap</h1>
            <p class="sub">
              A machine-readable sitemap for search engines, listing
              <strong><xsl:value-of select="count(s:urlset/s:url)"/></strong> pages on 9278.io.
            </p>
          </header>

          <div class="card">
            <table>
              <thead>
                <tr>
                  <th class="num">#</th>
                  <th>URL</th>
                  <th class="hide-sm">Priority</th>
                  <th class="hide-sm">Frequency</th>
                  <th class="hide-sm">Last modified</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="s:urlset/s:url">
                  <tr>
                    <td class="num"><xsl:value-of select="position()"/></td>
                    <td><a href="{s:loc}"><xsl:value-of select="s:loc"/></a></td>
                    <td class="hide-sm prio"><xsl:value-of select="s:priority"/></td>
                    <td class="hide-sm"><span class="pill"><xsl:value-of select="s:changefreq"/></span></td>
                    <td class="hide-sm muted"><xsl:value-of select="substring(s:lastmod,1,10)"/></td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </div>

          <p class="foot">
            Generated by <a href="https://9278.io">9278.io</a> · AI voice agents for India.
          </p>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
